### ISSUE TITLE
Fix roll command

### ISSUE THREAD

**Issue by ArchmageInc** [nomicness/a-whole-new-world#110]
The /roll command processor is not working:

`TypeError: methodName is not a function
    at /nomic-bot/dist/command-processors/roll-processor.js:58:22
    at /nomic-bot/node_modules/lodash/lodash.js:4573:15
    at baseForOwn (/nomic-bot/node_modules/lodash/lodash.js:2728:24)
    at /nomic-bot/node_modules/lodash/lodash.js:4542:18
    at Function.forEach (/nomic-bot/node_modules/lodash/lodash.js:8847:14)
    at processRoll (/nomic-bot/dist/command-processors/roll-processor.js:56:22)
    at /nomic-bot/dist/endpoint-processors/comment-processor.js:64:33
    at /nomic-bot/node_modules/multiple-methods/node_modules/lodash/index.js:8201:21
    at dispatcher (/nomic-bot/node_modules/multiple-methods/multi.js:14:52)
    at /nomic-bot/node_modules/multiple-methods/node_modules/lodash/index.js:8151:31`

**Comment by ArchmageInc** [comment]
The problem is that the roll subcommands used to be part of the processor, now they are part of the exports which means when we referenced them by name it used to be processor[methodName] and now we are trying to invoke methodName() which, of course, methodName is a string.
