### ISSUE TITLE
Happy

### ISSUE THREAD

**Issue by ArchmageInc** [nomicness/a-whole-new-world#116]
`TypeError: Cannot read property 'name' of undefined
    at /nomic-bot/dist/universe/world/base-world.js:116:49
    at Array.filter (native)
    at getCommentsForPlayer (/nomic-bot/dist/universe/world/base-world.js:115:34)
    at _callee$ (/nomic-bot/dist/universe/world/utils.js:23:32)
    at tryCatch (/nomic-bot/node_modules/regenerator-runtime/runtime.js:62:40)
    at GeneratorFunctionPrototype.invoke [as _invoke] (/nomic-bot/node_modules/regenerator-runtime/runtime.js:336:22)
    at GeneratorFunctionPrototype.prototype.(anonymous function) [as next] (/nomic-bot/node_modules/regenerator-runtime/runtime.js:95:21)
    at step (/nomic-bot/dist/universe/world/utils.js:48:191)
    at /nomic-bot/dist/universe/world/utils.js:48:361
    at process._tickCallback (internal/process/next_tick.js:103:7)`

**Comment by jimmyhmiller** [comment]
How did you make this happen?

**Comment by ArchmageInc** [comment]
by typing /happy in the audit history

**Comment by ArchmageInc** [comment]
`TypeError: Cannot read property 'comments_url' of undefined
    at getCommentsUrl (/nomic-bot/dist/universe/world/base-world.js:99:35)
    at _callee$ (/nomic-bot/dist/universe/world/utils.js:23:32)
    at tryCatch (/nomic-bot/node_modules/regenerator-runtime/runtime.js:62:40)
    at GeneratorFunctionPrototype.invoke [as _invoke] (/nomic-bot/node_modules/regenerator-runtime/runtime.js:336:22)
    at GeneratorFunctionPrototype.prototype.(anonymous function) [as next] (/nomic-bot/node_modules/regenerator-runtime/runtime.js:95:21)
    at step (/nomic-bot/dist/universe/world/utils.js:48:191)
    at /nomic-bot/dist/universe/world/utils.js:48:361
    at process._tickCallback (internal/process/next_tick.js:103:7)`

**Comment by ArchmageInc** [comment]
That happens when a comment is added to a code file

**Comment by ArchmageInc** [comment]
That might be a different issue

**Comment by jimmyhmiller** [comment]
I will look into it.

**Comment by jimmyhmiller** [comment]
This happens when nomic-bot posts a comment. I also know why happy is broken and I will fix it.

**Comment by ArchmageInc** [comment]
Happy is still broken, though no errors are being thrown.

**Comment by jimmyhmiller** [comment]
That's because I'm an idiot and got the condition backwards. If it is > 1 you can't do it. Will fix.

**Comment by jimmyhmiller** [comment]
Can't edit on mobile. Ignore what I said above.

**Comment by jimmyhmiller** [comment]
I know the solutions, but I'm still an idiot.
