### ISSUE TITLE
Unhappy

### ISSUE THREAD

**Issue by ArchmageInc** [nomicness/a-whole-new-world#129]
When attempting to run the /happy command the following error is displayed on the console:

```
TypeError: Cannot read property '1' of null
    at getLastPageNumber (/nomic-bot/dist/utils/github.js:86:78)
    at IncomingMessage.<anonymous> (/nomic-bot/dist/utils/github.js:71:27)
    at emitNone (events.js:91:20)
    at IncomingMessage.emit (events.js:185:7)
    at endReadableNT (_stream_readable.js:974:12)
    at _combinedTickCallback (internal/process/next_tick.js:74:11)
    at process._tickCallback (internal/process/next_tick.js:98:9)
```

**Comment by jimmyhmiller** [comment]
This has nothing to do with /happy. It is the  issue I was running into with page headers. I have a branch I think fixes it but I need to test more.  Branch: fix-link-headers
