### ISSUE TITLE
Allocation

### ISSUE THREAD

**Issue by ArchmageInc** [nomicness/a-whole-new-world#133]
TypeError: Cannot read property '1' of null
    at getLastPageNumber (/nomic-bot/dist/utils/github.js:86:78)
    at IncomingMessage.<anonymous> (/nomic-bot/dist/utils/github.js:71:27)
    at emitNone (events.js:91:20)
    at IncomingMessage.emit (events.js:185:7)
    at endReadableNT (_stream_readable.js:974:12)
    at _combinedTickCallback (internal/process/next_tick.js:74:11)
    at process._tickCallback (internal/process/next_tick.js:98:9)

**Comment by jimmyhmiller** [comment]
I hate this bug. But I'll get a fix in for it.
